# Generated by Django 5.2.13 on 2026-04-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('school', models.CharField(default='Wesley High School', max_length=120)),
                ('form_year', models.CharField(blank=True, max_length=50)),
                ('learning_style', models.CharField(blank=True, max_length=120)),
                ('short_intro', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('location', models.CharField(default='Dominica', max_length=120)),
                ('favorite_study_times', models.CharField(blank=True, max_length=160)),
                ('preferred_traits', models.ManyToManyField(blank=True, to='profiles.personalitytrait')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('subjects_needing_help', models.ManyToManyField(blank=True, related_name='students_needing_help', to='profiles.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_tutor', models.TextField(blank=True)),
                ('agrees_to_guidelines', models.BooleanField(default=False)),
                ('checklist_subject_confidence', models.BooleanField(default=False)),
                ('checklist_kind_communication', models.BooleanField(default=False)),
                ('checklist_safe_online_behavior', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tutor_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('school', models.CharField(default='Wesley High School', max_length=120)),
                ('form_year', models.CharField(blank=True, max_length=50)),
                ('short_bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tutors/')),
                ('tutoring_style', models.CharField(blank=True, max_length=160)),
                ('availability', models.CharField(blank=True, max_length=180)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('vibes_earned', models.PositiveIntegerField(default=0)),
                ('personality_traits', models.ManyToManyField(blank=True, to='profiles.personalitytrait')),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='profiles.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-average_rating', '-completed_sessions', 'full_name'],
            },
        ),
    ]
