# Generated by Django 5.2.13 on 2026-05-06 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_participants(apps, schema_editor):
    StudySession = apps.get_model('tutoring', 'StudySession')
    StudySessionParticipant = apps.get_model('tutoring', 'StudySessionParticipant')
    for session in StudySession.objects.all():
        StudySessionParticipant.objects.get_or_create(
            session=session,
            user=session.tutor,
            defaults={'role': 'lead_tutor', 'status': 'approved', 'approved_by': session.tutor},
        )
        StudySessionParticipant.objects.get_or_create(
            session=session,
            user=session.student,
            defaults={
                'role': 'student',
                'status': 'approved',
                'approved_by': session.tutor,
                'source_request': session.session_request,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lead_tutor', 'Lead tutor'), ('teacher', 'Teacher')], max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('removed', 'Removed')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_class_participants', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tutoring.studysession')),
                ('source_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_participant', to='tutoring.sessionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.RunPython(create_existing_participants, migrations.RunPython.noop),
    ]
